version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "eslint-plugin-storybook"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
